name: amazon_clone
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  dotted_border: ^2.0.0+3
  cloudinary_public: ^0.21.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/_rels/activity.svg
    - assets/_rels/airplay.svg
    - assets/_rels/alert-circle.svg
    - assets/_rels/alert-octagon.svg
    - assets/_rels/alert-triangle.svg
    - assets/_rels/align-center.svg
    - assets/_rels/align-justify.svg
    - assets/_rels/align-left.svg
    - assets/_rels/align-right.svg
    - assets/_rels/anchor.svg
    - assets/_rels/aperture.svg
    - assets/_rels/archive.svg
    - assets/_rels/arrow-down-circle.svg
    - assets/_rels/arrow-down-left.svg
    - assets/_rels/arrow-down-right.svg
    - assets/_rels/arrow-down.svg
    - assets/_rels/arrow-left-circle.svg
    - assets/_rels/arrow-left.svg
    - assets/_rels/arrow-right-circle.svg
    - assets/_rels/arrow-right.svg
    - assets/_rels/arrow-up-circle.svg
    - assets/_rels/arrow-up-left.svg
    - assets/_rels/arrow-up-right.svg
    - assets/_rels/arrow-up.svg
    - assets/_rels/at-sign.svg
    - assets/_rels/award.svg
    - assets/_rels/bar-chart-2.svg
    - assets/_rels/bar-chart.svg
    - assets/_rels/battery-charging.svg
    - assets/_rels/battery.svg
    - assets/_rels/bell-off.svg
    - assets/_rels/bell.svg
    - assets/_rels/bluetooth.svg
    - assets/_rels/bold.svg
    - assets/_rels/book-open.svg
    - assets/_rels/book.svg
    - assets/_rels/bookmark.svg
    - assets/_rels/box.svg
    - assets/_rels/briefcase.svg
    - assets/_rels/calendar.svg
    - assets/_rels/camera-off.svg
    - assets/_rels/camera.svg
    - assets/_rels/cast.svg
    - assets/_rels/check-circle.svg
    - assets/_rels/check-square.svg
    - assets/_rels/check.svg
    - assets/_rels/chevron-down.svg
    - assets/_rels/chevron-left.svg
    - assets/_rels/chevron-right.svg
    - assets/_rels/chevron-up.svg
    - assets/_rels/chevrons-down.svg
    - assets/_rels/chevrons-left.svg
    - assets/_rels/chevrons-right.svg
    - assets/_rels/chevrons-up.svg
    - assets/_rels/chrome.svg
    - assets/_rels/circle.svg
    - assets/_rels/clipboard.svg
    - assets/_rels/clock.svg
    - assets/_rels/cloud-drizzle.svg
    - assets/_rels/cloud-lightning.svg
    - assets/_rels/cloud-off.svg
    - assets/_rels/cloud-rain.svg
    - assets/_rels/cloud-snow.svg
    - assets/_rels/cloud.svg
    - assets/_rels/code.svg
    - assets/_rels/codepen.svg
    - assets/_rels/codesandbox.svg
    - assets/_rels/coffee.svg
    - assets/_rels/columns.svg
    - assets/_rels/command.svg
    - assets/_rels/compass.svg
    - assets/_rels/copy.svg
    - assets/_rels/corner-down-left.svg
    - assets/_rels/corner-down-right.svg
    - assets/_rels/corner-left-down.svg
    - assets/_rels/corner-left-up.svg
    - assets/_rels/corner-right-down.svg
    - assets/_rels/corner-right-up.svg
    - assets/_rels/corner-up-left.svg
    - assets/_rels/corner-up-right.svg
    - assets/_rels/cpu.svg
    - assets/_rels/credit-card.svg
    - assets/_rels/crop.svg
    - assets/_rels/crosshair.svg
    - assets/_rels/database.svg
    - assets/_rels/delete.svg
    - assets/_rels/disc.svg
    - assets/_rels/divide-circle.svg
    - assets/_rels/divide-square.svg
    - assets/_rels/divide.svg
    - assets/_rels/dollar-sign.svg
    - assets/_rels/download-cloud.svg
    - assets/_rels/download.svg
    - assets/_rels/dribbble.svg
    - assets/_rels/droplet.svg
    - assets/_rels/edit-2.svg
    - assets/_rels/edit-3.svg
    - assets/_rels/edit.svg
    - assets/_rels/external-link.svg
    - assets/_rels/eye-off.svg
    - assets/_rels/eye.svg
    - assets/_rels/facebook.svg
    - assets/_rels/fast-forward.svg
    - assets/_rels/feather.svg
    - assets/_rels/figma.svg
    - assets/_rels/file-minus.svg
    - assets/_rels/file-plus.svg
    - assets/_rels/file-text.svg
    - assets/_rels/file.svg
    - assets/_rels/film.svg
    - assets/_rels/filter.svg
    - assets/_rels/flag.svg
    - assets/_rels/folder-minus.svg
    - assets/_rels/folder-plus.svg
    - assets/_rels/folder.svg
    - assets/_rels/framer.svg
    - assets/_rels/frown.svg
    - assets/_rels/gift.svg
    - assets/_rels/git-branch.svg
    - assets/_rels/git-commit.svg
    - assets/_rels/git-merge.svg
    - assets/_rels/git-pull-request.svg
    - assets/_rels/github.svg
    - assets/_rels/gitlab.svg
    - assets/_rels/globe.svg
    - assets/_rels/grid.svg
    - assets/_rels/hard-drive.svg
    - assets/_rels/hash.svg
    - assets/_rels/headphones.svg
    - assets/_rels/heart.svg
    - assets/_rels/help-circle.svg
    - assets/_rels/hexagon.svg
    - assets/_rels/home.svg
    - assets/_rels/image.svg
    - assets/_rels/inbox.svg
    - assets/_rels/info.svg
    - assets/_rels/instagram.svg
    - assets/_rels/italic.svg
    - assets/_rels/key.svg
    - assets/_rels/layers.svg
    - assets/_rels/layout.svg
    - assets/_rels/life-buoy.svg
    - assets/_rels/link-2.svg
    - assets/_rels/link.svg
    - assets/_rels/linkedin.svg
    - assets/_rels/list.svg
    - assets/_rels/loader.svg
    - assets/_rels/lock.svg
    - assets/_rels/log-in.svg
    - assets/_rels/log-out.svg
    - assets/_rels/mail.svg
    - assets/_rels/map-pin.svg
    - assets/_rels/map.svg
    - assets/_rels/maximize-2.svg
    - assets/_rels/maximize.svg
    - assets/_rels/meh.svg
    - assets/_rels/menu.svg
    - assets/_rels/message-circle.svg
    - assets/_rels/message-square.svg
    - assets/_rels/mic-off.svg
    - assets/_rels/mic.svg
    - assets/_rels/minimize-2.svg
    - assets/_rels/minimize.svg
    - assets/_rels/minus-circle.svg
    - assets/_rels/minus-square.svg
    - assets/_rels/minus.svg
    - assets/_rels/monitor.svg
    - assets/_rels/moon.svg
    - assets/_rels/more-horizontal.svg
    - assets/_rels/more-vertical.svg
    - assets/_rels/mouse-pointer.svg
    - assets/_rels/move.svg
    - assets/_rels/music.svg
    - assets/_rels/navigation-2.svg
    - assets/_rels/navigation.svg
    - assets/_rels/octagon.svg
    - assets/_rels/package.svg
    - assets/_rels/paperclip.svg
    - assets/_rels/pause-circle.svg
    - assets/_rels/pause.svg
    - assets/_rels/pen-tool.svg
    - assets/_rels/percent.svg
    - assets/_rels/phone-call.svg
    - assets/_rels/phone-forwarded.svg
    - assets/_rels/phone-incoming.svg
    - assets/_rels/phone-missed.svg
    - assets/_rels/phone-off.svg
    - assets/_rels/phone-outgoing.svg
    - assets/_rels/phone.svg
    - assets/_rels/pie-chart.svg
    - assets/_rels/play-circle.svg
    - assets/_rels/play.svg
    - assets/_rels/plus-circle.svg
    - assets/_rels/plus-square.svg
    - assets/_rels/plus.svg
    - assets/_rels/pocket.svg
    - assets/_rels/power.svg
    - assets/_rels/printer.svg
    - assets/_rels/radio.svg
    - assets/_rels/refresh-ccw.svg
    - assets/_rels/refresh-cw.svg
    - assets/_rels/repeat.svg
    - assets/_rels/rewind.svg
    - assets/_rels/rotate-ccw.svg
    - assets/_rels/rotate-cw.svg
    - assets/_rels/rss.svg
    - assets/_rels/save.svg
    - assets/_rels/scissors.svg
    - assets/_rels/search.svg
    - assets/_rels/send.svg
    - assets/_rels/server.svg
    - assets/_rels/settings.svg
    - assets/_rels/share-2.svg
    - assets/_rels/share.svg
    - assets/_rels/shield-off.svg
    - assets/_rels/shield.svg
    - assets/_rels/shopping-bag.svg
    - assets/_rels/shopping-cart.svg
    - assets/_rels/shuffle.svg
    - assets/_rels/sidebar.svg
    - assets/_rels/skip-back.svg
    - assets/_rels/skip-forward.svg
    - assets/_rels/slack.svg
    - assets/_rels/slash.svg
    - assets/_rels/sliders.svg
    - assets/_rels/smartphone.svg
    - assets/_rels/smile.svg
    - assets/_rels/speaker.svg
    - assets/_rels/square.svg
    - assets/_rels/star.svg
    - assets/_rels/stop-circle.svg
    - assets/_rels/sun.svg
    - assets/_rels/sunrise.svg
    - assets/_rels/sunset.svg
    - assets/_rels/table.svg
    - assets/_rels/tablet.svg
    - assets/_rels/tag.svg
    - assets/_rels/target.svg
    - assets/_rels/terminal.svg
    - assets/_rels/thermometer.svg
    - assets/_rels/thumbs-down.svg
    - assets/_rels/thumbs-up.svg
    - assets/_rels/toggle-left.svg
    - assets/_rels/toggle-right.svg
    - assets/_rels/tool.svg
    - assets/_rels/trash-2.svg
    - assets/_rels/trash.svg
    - assets/_rels/trello.svg
    - assets/_rels/trending-down.svg
    - assets/_rels/trending-up.svg
    - assets/_rels/triangle.svg
    - assets/_rels/truck.svg
    - assets/_rels/tv.svg
    - assets/_rels/twitch.svg
    - assets/_rels/twitter.svg
    - assets/_rels/type.svg
    - assets/_rels/umbrella.svg
    - assets/_rels/underline.svg
    - assets/_rels/unlock.svg
    - assets/_rels/upload-cloud.svg
    - assets/_rels/upload.svg
    - assets/_rels/user-check.svg
    - assets/_rels/user-minus.svg
    - assets/_rels/user-plus.svg
    - assets/_rels/user-x.svg
    - assets/_rels/user.svg
    - assets/_rels/users.svg
    - assets/_rels/video-off.svg
    - assets/_rels/video.svg
    - assets/_rels/voicemail.svg
    - assets/_rels/volume-1.svg
    - assets/_rels/volume-2.svg
    - assets/_rels/volume-x.svg
    - assets/_rels/volume.svg
    - assets/_rels/watch.svg
    - assets/_rels/wifi-off.svg
    - assets/_rels/wifi.svg
    - assets/_rels/wind.svg
    - assets/_rels/x-circle.svg
    - assets/_rels/x-octagon.svg
    - assets/_rels/x-square.svg
    - assets/_rels/x.svg
    - assets/_rels/youtube.svg
    - assets/_rels/zap-off.svg
    - assets/_rels/zap.svg
    - assets/_rels/zoom-in.svg
    - assets/_rels/zoom-out.svg
    - assets/images/PhotoSharing.png
    - assets/images/Pizzamaker.png
    - assets/images/Referafriend.png
    - assets/images/amazon_in.png
    - assets/images/books.jpeg
    - assets/images/electronics.jpeg
    - assets/images/essentials.jpeg
    - assets/images/fashion.jpeg
    - assets/images/mobiles.jpeg
